%YAML:1.0

# /////////////////////////
# // IONLAB ISAE-SUPAERO //
# // TELLO SLAM PROJECT  //
# /////////////////////////

# Mode ////////////////////////////////////////////////////////////////////////
# test, mission
mode: test

verbose: 1

# Input ///////////////////////////////////////////////////////////////////////
# usb, video, tello
input_mode: usb

# USB Camera
USB_camera_ID: 2

# Setting
setting_file_path: ./config/sensor_setting.yaml

# Video
video_file_path: /media/tershire/Samsung_T3/VIDEO/ionmav/20230807_release_test.mp4

# Tello
tello_video_stream: "udp://0.0.0.0:11111"

# image size
mono_camera_scale_factor: 1.0

# Output //////////////////////////////////////////////////////////////////////
resize_scale_factor: 0.75

# System //////////////////////////////////////////////////////////////////////
# which camera type is used for the mono camera: usb, raspberry
mono_camera_type: usb

# Aruco Detector //////////////////////////////////////////////////////////////
predifined_dictionary_name: DICT_5X5_50
marker_length: 14.5E-2

# Door Detector ///////////////////////////////////////////////////////////////
# model_path ex) ./models/yolov8s.onnx
# names_path ex) ./config/coco.names
model_path: ./models/yolov8n_door_run5.onnx 
names_path: ./config/door.names 
enable_CUDA: 0 # 1 for true, 0 for false (1 currently not supported)

score_threshold: 0.5
confidence_threshold: 0.5
nms_threshold: 0.5

# Supervisor //////////////////////////////////////////////////////////////////
# motion log __________________________________________________________________
motion_log_on: 1 # 1 for true, 0 for false (if timestamps are not provided, set to false)
