%YAML:1.0

# /////////////////////////
# // IONLAB ISAE-SUPAERO //
# // TELLO SLAM PROJECT  //
# /////////////////////////

# Input ///////////////////////////////////////////////////////////////////////
# usb, video
input_mode: usb

# USB Camera
USB_camera_ID: 0

# Video
video_file_path: /media/tershire/Samsung_T3/VIDEO/ionmav/20230807_release_test.mp4

# Output //////////////////////////////////////////////////////////////////////
resize_scale_factor: 0.75

# Aruco Detector //////////////////////////////////////////////////////////////
predifined_dictionary_name: DICT_5X5_50
marker_length: 14.5E-2
